// Scroll choreography. One chapter per screen; `s` runs 0 → chapters.length - 1.
// Camera: target (mm), distance (mm), azimuth/elevation (deg), shift = horizontal
// screen offset (fraction of width) to leave room for the text card.
export const chapters = [
  {
    kicker: 'Leica M6 · 1984',
    title: 'Anatomy of a<br><em>rangefinder</em>',
    body: 'Scroll to take a mechanical camera apart, one part at a time. Everything you see is modelled, lit and machined in real time, in your browser.',
    side: 'left',
    cam: { t: [0, 0, 8], d: 430, az: -34, el: 16, shift: 0.2 },
    labels: [['redDot', 'Red dot'], ['vfWindow', 'Viewfinder window'], ['rfWindow', 'Rangefinder window']],
  },
  {
    kicker: '01 — Lens',
    title: 'Summilux-M<br><em>50 f/1.4</em>',
    body: 'A quarter turn and the lens leaves the M bayonet. A cam on its rear follows the focusing helicoid and tells the rangefinder exactly where you are focused.',
    side: 'right',
    cam: { t: [0, -6, 70], d: 500, az: 58, el: 10, shift: -0.25 },
    labels: [['bayonet', 'M bayonet'], ['focusRing', 'Focus ring & tab'], ['apertureRing', 'Aperture ring'], ['mount', 'Body mount · 27.8 mm flange']],
  },
  {
    kicker: '02 — Optics',
    title: 'Eight pieces<br><em>of glass</em>',
    body: 'The barrel rings slide away and the optics hang in place. Cemented pairs sit either side of the aperture; the rear element is aspherical. Light converges 27.8 mm behind the mount, exactly on the film.',
    side: 'left',
    cam: { t: [0, -9, 118], d: 500, az: 90, el: 6, shift: 0.2 },
    labels: [['element1', 'Front element'], ['doublet', 'Cemented doublet'], ['doublet2', 'Rear doublet'], ['asph', 'Aspherical element'], ['frontBarrel', 'Front barrel'], ['focusRing', 'Focusing helicoid']],
  },
  {
    kicker: '03 — Aperture',
    title: 'The iris',
    body: 'Ten blackened steel blades swing on pins to close the opening. Every full stop halves the light reaching the film.',
    side: 'left',
    readout: 'fstop',
    cam: { t: [0, -67, 126], d: 150, az: 16, el: 6, shift: 0.22 },
    labels: [['iris', 'Blade assembly']],
  },
  {
    kicker: '04 — Top plate',
    title: 'Machined,<br><em>then plated</em>',
    body: 'The top plate lifts away with its controls: the shutter speed dial, a release threaded for a cable, and the advance lever that cocks the shutter and moves the film in one stroke. Below, a brass gear train does the work.',
    side: 'left',
    cam: { t: [0, 64, 0], d: 560, az: -30, el: 30, shift: 0.2 },
    labels: [['topPlate', 'Top plate'], ['speedDial', 'Shutter speed dial'], ['advance', 'Advance lever'], ['release', 'Shutter release'], ['rewind', 'Rewind crank'], ['hotShoe', 'Hot shoe'], ['gears', 'Transport gear train']],
  },
  {
    kicker: '05 — Rangefinder',
    title: 'Two images,<br><em>one truth</em>',
    body: 'Light from the small window strikes a swinging mirror and is folded into the viewfinder by a beam splitter. Turn the focus ring, the mirror rotates, and the two images slide into one. Bright-line frames show what each lens sees.',
    side: 'right',
    cam: { t: [4, 78, 0], d: 480, az: 32, el: 22, shift: -0.2 },
    labels: [['frameMask', 'Bright-line frame mask'], ['beamSplitter', 'Beam splitter'], ['rfMirror', 'Rangefinder mirror'], ['objective', 'Viewfinder objective'], ['roller', 'Cam follower'], ['pcb', 'Light-meter board'], ['photodiode', 'Photodiode'], ['eyeLens', 'Eyepiece optic']],
  },
  {
    kicker: '06 — Chassis',
    title: 'Die-cast core,<br><em>vulcanite skin</em>',
    body: 'Under the pebbled covering, a rigid die-cast body holds the mount, gate and film rails in exact alignment. Two button cells power the meter. Nothing else in the camera needs electricity.',
    side: 'left',
    cam: { t: [0, 8, -18], d: 580, az: 140, el: 16, shift: 0.2 },
    labels: [['vulcanite', 'Vulcanite covering'], ['throat', 'Light baffles'], ['pressurePlate', 'Pressure plate'], ['isoDial', 'Film-speed reminder'], ['battery', '2 × SR44 cells'], ['lensRelease', 'Lens release'], ['frameSelector', 'Frame selector'], ['strapLug', 'Strap lug']],
  },
  {
    kicker: '07 — Shutter',
    title: 'Cloth,<br><em>in a hurry</em>',
    body: 'A horizontal focal-plane shutter with rubberised cloth curtains. The first curtain opens, the second chases it, and the gap between them sets the exposure, from 1 s to 1/1000 s. The white spot is what the meter reads.',
    side: 'right',
    cam: { t: [0, -6, -40], d: 290, az: 158, el: 10, shift: -0.2 },
    labels: [['shutterFrame', 'Shutter crate'], ['meterSpot', 'Metering spot'], ['drum', 'Curtain drum'], ['rails', 'Film rails']],
  },
  {
    kicker: '08 — Film',
    title: 'Thirty-six<br><em>frames</em>',
    body: 'Turn the key, drop the base plate, and the film path appears: cassette, gate and take-up spool. The spring-loaded pressure plate keeps the film flat against the rails.',
    side: 'left',
    cam: { t: [0, -58, -12], d: 540, az: -142, el: 14, shift: 0.2 },
    labels: [['cassette', '35 mm cassette'], ['takeUp', 'Take-up spool'], ['filmStrip', 'Film · 36 × 24 mm frames'], ['basePlate', 'Base plate'], ['lockKey', 'Locking key']],
  },
  {
    kicker: '09 — Everything',
    title: '<span data-parts>—</span> parts,<br><em>one instrument</em>',
    body: 'Every component at once. Drag to turn it around.',
    side: 'left',
    cam: { t: [0, 36, 40], d: 1080, az: -40, el: 18, shift: 0.12, orbit: 55 },
    labels: [['topPlate', 'Top plate'], ['frontBarrel', 'Lens'], ['shutterFrame', 'Shutter'], ['cassette', 'Film'], ['frameMask', 'Rangefinder'], ['basePlate', 'Base plate']],
  },
  {
    kicker: 'Reassembled',
    title: 'Made to outlast<br><em>its owner</em>',
    body: '',
    side: 'right',
    specs: true,
    cam: { t: [0, 0, 8], d: 440, az: 32, el: 14, shift: -0.2 },
    labels: [],
  },
];

export const specs = [
  ['Type', '35 mm rangefinder'],
  ['Shutter', 'Cloth focal-plane, 1–1/1000 s'],
  ['Flash sync', '1/50 s'],
  ['Viewfinder', '0.72×, bright-line frames'],
  ['Metering', 'TTL, centre-weighted, LED'],
  ['Power', '2 × SR44 (meter only)'],
  ['Weight', '≈ 560 g body'],
];
